insert into PRODUCTS(PRODUCT_ID, BOL_DESC, PRODUCT_DESC) values('NACNL', 'NACNL BOL DESC', 'NACNL DESC');
insert into PRODUCTS(PRODUCT_ID, BOL_DESC, PRODUCT_DESC) values('NACNB', 'NACNB BOL DESC', 'NACNB DESC');
insert into PRODUCTS(PRODUCT_ID, BOL_DESC, PRODUCT_DESC) values('NACNH', 'NACNH BOL DESC', 'NACNH DESC');
insert into COMPANIES(COMPANY_ID, COMPANY_NAME) values('POSABRO','POSABRO S.A. de C.V.');
insert into BRANCHES(COMPANY_ID, BRANCH_ID) values('POSABRO', 'COAHUILA BRANCH');
